import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// import { calculateFourPillars, fourPillarsToString } from "manseryeok";

// // 양력 날짜로 사주 계산
// const result = calculateFourPillars({
//   year: 1998, // 연도 (양력)
//   month: 1, // 월 (양력, 1-12)
//   day: 21, // 일 (양력, 1-31)
//   hour: 5, // 시 (24시간제, 0-23)
//   minute: 30, // 분 (0-59)
// });

// console.log(result);
// console.log(result.toString());
// console.log(result.toObject());
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
